# Use root/example as user/password credentials
version: '3.4'

services:

  db:
    build:
      context: ./db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    volumes:
      - data:/var/lib/mysql
    ports:
      - "33306:3306"
  web:
    depends_on:
      - db
    build:
      context: ./web
      network: host
    restart: always
    ports:
      - "9980:80"

volumes:
  data: